### ISSUE TITLE
Automatic channel ID retrieval

### ISSUE THREAD

**Issue by 2Cubed** [RPiAwesomeness/BeamBot#1]
As a feature request, it would be neat to have the program initially grab the channel ID (you can parse the data using the built-in Python json module). In addition to making life easier, you can also do an initial test to make sure that internet is available. :smile:

**Comment by RPiAwesomeness** [comment]
Good idea! Will definitely look into doing this.

**Comment by RPiAwesomeness** [comment]
@2Cubed Added in commit ef9ed44 (v2.1.0)!

pybot will now do one of two of things.

1. Its new default behavior is to automatically ask you for the channel's name. It then retrieves the correct channel ID for this specific session and connects to that channel.
2. You can change the configuration around to make it auto-connect to a certain channel.
